# Generated by Django 5.0.6 on 2024-07-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZombieTapApp', '0012_alter_customuser_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
    ]
