# Generated by Django 5.0.6 on 2024-07-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZombieTapApp', '0016_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_photo',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
