# Generated by Django 5.0.6 on 2024-07-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZombieTapApp', '0022_alter_users_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_photo',
            new_name='user_photo_url',
        ),
    ]
