# Generated by Django 5.0.6 on 2024-07-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZombieTapApp', '0023_rename_user_photo_users_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_photo_url',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
