# Generated by Django 5.0.6 on 2024-07-28 08:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZombieTapApp', '0025_alter_users_user_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hurt_limit_lvl',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=5),
        ),
        migrations.AddField(
            model_name='users',
            name='last_game',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='multitap_lvl',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=5),
        ),
        migrations.AddField(
            model_name='users',
            name='regeneration_lvl',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=5),
        ),
    ]
