# Generated by Django 5.0.6 on 2024-07-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZombieTapApp', '0026_users_hurt_limit_lvl_users_last_game_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
