# Generated by Django 5.0.6 on 2024-08-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZombieTapApp', '0030_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
